apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: blogpost-model
  namespace: seldon
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: transformer
          image: <IMAGE_NAME>
    graph:
      name: transformer
      type: MODEL
      endpoint:
        service_port: 5000
    name: model
    replicas: 1
